version: '3.9'
services:
  transpo:
    image: transpo
    ports:
      - "8123:8123/tcp"
    environment:
      - TRANSPO_MAX_UPLOAD_AGE_MINUTES=10080
      - TRANSPO_MAX_UPLOAD_SIZE_BYTES=5_000_000_000
      - TRANSPO_MAX_STORAGE_SIZE_BYTES=200_000_000_000
      - TRANSPO_COMPRESSION_LEVEL=0
      - TRANSPO_QUOTA_BYTES=5_100_000_000
      - TRANSPO_QUOTA_INTEVAL_MINUTES=60
      - TRANSPO_READ_TIMEOUT_MILLISECONDS=500
      - TRANSPO_DATABASE_URL=/transpo_storage/db.sqlite
      - TRANSPO_APP_NAME=Transpo
    build:
      context: .
      args:
        - TRANSPO_STORAGE_DIRECTORY=/transpo_storage
    volumes:
      - storage:/transpo_storage
volumes:
  storage:
